//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importusers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustMeterPoints
    {
        public int RecId { get; set; }
        public string KontAccountId { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string PostCode { get; set; }
        public string Corp { get; set; }
        public string FlatNumber { get; set; }
        public string EICCode { get; set; }
        public string SerialNumber { get; set; }
        public string CompanyId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
