//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importusers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustAccounts
    {
        public string KontAccountId { get; set; }
        public string CompanyId { get; set; }
        public string CustAccountId { get; set; }
        public string WorksId { get; set; }
        public string WorksName { get; set; }
        public string CustType { get; set; }
        public string GreenTariff { get; set; }
        public string CustId { get; set; }
        public int RecId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
