//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importusers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngChatTable
    {
        public string UserDialogId { get; set; }
        public int RecId { get; set; }
        public string Login { get; set; }
        public string TextMessage { get; set; }
        public string StateId { get; set; }
        public string TempStateId { get; set; }
        public string LanguageId { get; set; }
        public string CompanyId { get; set; }
        public string CustId { get; set; }
        public string MessengerType { get; set; }
        public string ChatId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    
        public virtual CustTable CustTable { get; set; }
    }
}
