//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importusers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatBotAppDataBaseTestEntities : DbContext
    {
        public ChatBotAppDataBaseTestEntities()
            : base("name=ChatBotAppDataBaseTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustAccounts> CustAccounts { get; set; }
        public virtual DbSet<CustMeterPoints> CustMeterPoints { get; set; }
        public virtual DbSet<CustTable> CustTable { get; set; }
        public virtual DbSet<EngChatTable> EngChatTable { get; set; }
    }
}
