//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importusers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRelocationData
    {
        public int id { get; set; }
        public string r { get; set; }
        public string t { get; set; }
        public string y { get; set; }
    }
}
